### ISSUE TITLE
Valid Prisma 2+ schema is seen as invalid and halts the complete migration

### ISSUE THREAD

**Issue by jw** [prisma/upgrade#149]
When migrating our Prisma 1 to latest, our introspected schema is not seen as valid.

1. We created a new Prisma environment with the `yarn prisma init` command, just as specified in the documentation.

2. After a `yarn prisma db pull`, we saw the created schema in `prisma/schema.prisma`.
 
3. A `yarn prisma validate` reported that the freshly created `schema.prisma` was valid.
 
4. The `yarn prisma-upgrade prisma1/prisma.yml prisma/schema.prisma` reported:   

```
Error Error parsing the Prisma 2 file.

Are you sure "/home/jw/projects/graphql/prisma/schema.prisma" is a valid Prisma 2 schema file?
```

**Comment by janpio** [comment]
You might want to use an older Prisma version, not the latest Prisma 4.x. Since this tool was created, Prisma Schema got a few additions that it can not handle (and will not be updated to).

Start with 3.x and see if that validates, if not go back a bit further until you hit one that works. Then you can do the upgrade with that version, and then do another upgrade later to the newest Prisma 4+.

**Comment by janpio** [comment]
(Parallel discussion in Slack: https://prisma.slack.com/archives/C0152UA4DH9/p1671533194688039)

**Comment by jw** [comment]
Indeed, with the invaluable help of Muhammad Usman we found out that Prisma 4 creates a valid schema when doing a `db pull`.  But that schema is not valid for the `prisma-upgarde`.  When running the `dp pull` on the Prisma 3, the resulting schema can be read by the `prisma-upgrade`.

**Comment by jw** [comment]
Might be a nice thing add this to both the `prisma-upgrade` and the prisma website documentation sections.

**Comment by janpio** [comment]
What version exactly did you use?
